name: "Build NuvlaEdge Common Library"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'nuvlaedge/'
      - 'tests/'
      - '.github/workflows/main.yml'

jobs:
  build-library:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: SetUp python interpreter
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: SetUp poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.2.2"

      - name: Build package
        run: poetry build --format=wheel

      - name: Find package name and version
        run: |
          cd dist/
          echo "PACKAGE_NAME=$(ls nuvlaedge_common-*.whl)" >> $GITHUB_ENV

      # Use QeMu for multi-architecture build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Docker meta
#        id: metadata # you'll use this in the next step
#        uses: docker/metadata-action@v3
#        with:
#          # list of Docker images to use as base name for tags
#          images: |
#            nuvlaedge-common
#          # Docker tags based on the following events/attributes
#          tags: |
#            type=schedule
#            type=ref,event=branch
#            type=ref,event=pr
#            type=semver,pattern={{version}}
#            type=semver,pattern={{major}}.{{minor}}
#            type=semver,pattern={{major}}
#            type=sha

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm/v8,linux/arm64
          build-args: |
            GIT_BRANCH=${{ github.ref_name }}
            GIT_BUILD_TIME=$(date --utc +%FT%T.%3NZ)
            GIT_COMMIT_ID=${{ github.sha }}
            GITHUB_RUN_NUMBER=${{ github.run_number }}
            GITHUB_RUN_ID=${{ github.run_id }}
            PROJECT_URL=${{ github.server_url }}/${{ github.repository }}
            PACKAGE_NAME=${{ env.PACKAGE_NAME }}

          tags: nuvladev/nuvlaedge-base:${{ github.ref_name }},nuvladev/nuvlaedge-base:latest
          push: true

